velocity_smoother:
  ros__parameters:
    smoothing_frequency: 20.0
    scale_velocities: false
    feedback: "OPEN_LOOP"
    max_velocity: [0.20, 0.0, 0.65]
    min_velocity: [-0.12, 0.0, -0.65]
    max_accel: [0.25, 0.0, 0.8]
    max_decel: [-0.35, 0.0, -0.8]
    odom_topic: "/odom"
    odom_duration: 0.1
    deadband_velocity: [0.0, 0.0, 0.0]
    velocity_timeout: 0.3
