[pytest]
markers =
    ros_required: test imports ROS 2 Python packages or ROS message types
    requires_ros: alias for ros_required
    linter: package lint test
    copyright: package copyright test
    flake8: flake8 style test
    pep257: docstring style test
