#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
# shellcheck source=scripts/waver_field_env_load.sh
source "${ROOT}/scripts/waver_field_env_load.sh"

START=false
NO_BOOTSTRAP=false
DRY_RUN=false
FORCE=false

while [ "$#" -gt 0 ]; do
  case "$1" in
    --jetson-host) JETSON_HOST="$2"; shift 2 ;;
    --jetson-user) JETSON_USER="$2"; shift 2 ;;
    --jetson-port) JETSON_PORT="$2"; shift 2 ;;
    --jetson-ws) JETSON_WS="$2"; shift 2 ;;
    --container) CONTAINER="$2"; shift 2 ;;
    --ros-domain-id) ROS_DOMAIN_ID="$2"; shift 2 ;;
    --serial-port) SERIAL_PORT="$2"; shift 2 ;;
    --livox-host-ip) LIVOX_HOST_IP="$2"; shift 2 ;;
    --livox-sensor-ip) LIVOX_SENSOR_IP="$2"; shift 2 ;;
    --livox-bd-code) LIVOX_BD_CODE="$2"; shift 2 ;;
    --field-build-in-docker) FIELD_BUILD_IN_DOCKER="$2"; shift 2 ;;
    --start) START=true; shift ;;
    --no-bootstrap) NO_BOOTSTRAP=true; shift ;;
    --dry-run) DRY_RUN=true; shift ;;
    --force) FORCE=true; shift ;;
    -h|--help)
      sed -n '1,80p' "${ROOT}/docs/CLONE_TO_FIELD.md"
      exit 0
      ;;
    *) echo "[QUICKSTART][ERROR] unknown arg: $1" >&2; exit 2 ;;
  esac
done

LOCAL_ENV="${ROOT}/config/waver_field_env.local"
if [ -f "${LOCAL_ENV}" ] && [ "${FORCE}" != "true" ]; then
  echo "[QUICKSTART] keeping existing config/waver_field_env.local; use --force to overwrite"
else
  echo "[QUICKSTART] writing config/waver_field_env.local"
  {
    echo "# Generated by waver_quickstart_field.sh. Do not commit this file."
    echo "JETSON_HOST=${JETSON_HOST}"
    echo "JETSON_USER=${JETSON_USER}"
    echo "JETSON_PORT=${JETSON_PORT:-22}"
    echo "JETSON_WS=${JETSON_WS}"
    echo "CONTAINER=${CONTAINER}"
    echo "ROS_DOMAIN_ID=${ROS_DOMAIN_ID}"
    echo "RMW_IMPLEMENTATION=${RMW_IMPLEMENTATION:-rmw_cyclonedds_cpp}"
    echo "SERIAL_PORT=${SERIAL_PORT}"
    echo "LIVOX_HOST_IP=${LIVOX_HOST_IP:-}"
    echo "LIVOX_SENSOR_IP=${LIVOX_SENSOR_IP:-}"
    echo "LIVOX_FRAME_ID=${LIVOX_FRAME_ID:-livox}"
    echo "LIVOX_POINTCLOUD_TOPIC=${LIVOX_POINTCLOUD_TOPIC:-/livox/lidar}"
    echo "LIVOX_IMU_TOPIC=${LIVOX_IMU_TOPIC:-/livox/imu}"
    echo "POINTCLOUD_TOPIC=${POINTCLOUD_TOPIC:-${LIVOX_POINTCLOUD_TOPIC:-/livox/lidar}}"
    echo "LIVOX_BD_CODE=${LIVOX_BD_CODE:-}"
    echo "FIELD_BUILD_IN_DOCKER=${FIELD_BUILD_IN_DOCKER:-auto}"
  } > "${LOCAL_ENV}"
fi

if [ ! -f "${ROOT}/.env" ] && [ -f "${ROOT}/.env.example" ]; then
  cp "${ROOT}/.env.example" "${ROOT}/.env"
fi

if [ "${DRY_RUN}" = "true" ]; then
  echo "[QUICKSTART] dry run complete"
  waver_field_env_masked_summary
  exit 0
fi

bash "${ROOT}/scripts/waver_doctor.sh"

if [ "${NO_BOOTSTRAP}" != "true" ]; then
  bash "${ROOT}/scripts/waver_field_bootstrap_jetson.sh"
fi

echo "[QUICKSTART] Next commands:"
echo "  bash scripts/waver_start_field_backend.sh"
echo "  bash scripts/waver_start_local_ui.sh"

if [ "${START}" = "true" ]; then
  bash "${ROOT}/scripts/waver_start_field_backend.sh"
  bash "${ROOT}/scripts/waver_start_local_ui.sh"
fi
