from glob import glob
from setuptools import find_packages, setup

package_name = 'waver_patrol'

setup(
    name=package_name,
    version='0.1.0',
    packages=find_packages(exclude=['test']),
    data_files=[
        ('share/ament_index/resource_index/packages',
            ['resource/' + package_name]),
        ('share/' + package_name, ['package.xml']),
        ('share/' + package_name + '/config', glob('config/*.yaml')),
        ('share/' + package_name + '/launch', glob('launch/*.launch.py')),
        ('share/' + package_name + '/waypoints', glob('waypoints/*.yaml')),
        ('share/' + package_name + '/maps', glob('maps/*')),
        ('share/' + package_name + '/scripts', glob('scripts/*.sh') + glob('scripts/*.py')),
        ('share/' + package_name + '/docs', glob('docs/*.md')),
        ('share/' + package_name + '/data', glob('data/*.md')),
        ('share/' + package_name + '/data/schema', glob('data/schema/*.csv')),
    ],
    install_requires=['setuptools'],
    zip_safe=True,
    maintainer='chotaehyun',
    maintainer_email='whxogus4793@naver.com',
    description='Safety-first patrol, teleop, and Nav2 wrappers for the Waver outdoor patrol robot.',
    license='Apache-2.0',
    extras_require={
        'test': [
            'pytest',
        ],
    },
    entry_points={
        'console_scripts': [
            'inspect_stack = waver_patrol.apps.inspect_stack:main',
            'teleop_keyboard = waver_patrol.apps.teleop_keyboard:main',
            'stop_robot = waver_patrol.apps.stop_robot:main',
            'sensor_check = waver_patrol.apps.sensor_check:main',
            'mapping_2d = waver_patrol.apps.mapping_2d:main',
            'mapping_3d = waver_patrol.apps.mapping_3d:main',
            'save_map = waver_patrol.apps.save_map:main',
            'localization = waver_patrol.apps.localization:main',
            'nav2_demo = waver_patrol.apps.nav2_demo:main',
            'patrol_run = waver_patrol.apps.patrol_run:main',
            'slam_nav_patrol = waver_patrol.apps.slam_nav_patrol:main',
            'risk_self_test = waver_patrol.apps.risk_self_test:main',
            'serial_cmd_vel_bridge = waver_patrol.bridges.serial_cmd_vel_bridge:main',
            'cmd_vel_to_json = waver_patrol.bridges.cmd_vel_to_json:main',
            'teleop_node = waver_patrol.teleop.teleop_node:main',
            'fixed_waypoint_patrol_node = waver_patrol.patrol.fixed_waypoint_patrol_node:main',
            'battery_return_manager_node = waver_patrol.patrol.battery_return_manager_node:main',
            'return_home_controller_node = waver_patrol.patrol.return_home_controller_node:main',
            'lidar_aerial_motion_detector_node = waver_patrol.perception.lidar_aerial_motion_detector_node:main',
            'livox_pointcloud_to_scan_node = waver_patrol.perception.livox_pointcloud_to_scan_node:main',
            'pointcloud_lidar_objects_node = waver_patrol.perception.pointcloud_lidar_objects_node:main',
            'moving_object_map_transform_node = waver_patrol.perception.moving_object_map_transform_node:main',
            'moving_object_goal_relay_node = waver_patrol.perception.moving_object_goal_relay_node:main',
            'target_body_tracker_node = waver_patrol.control.target_body_tracker_node:main',
            'auto_behavior_mux_node = waver_patrol.control.auto_behavior_mux_node:main',
            'safety_cmd_mux_node = waver_patrol.safety.safety_cmd_mux_node:main',
            'gazebo_bird_pose_bridge_node = waver_patrol.bridges.gazebo_bird_pose_bridge_node:main',
            'deep_learning_bridge_stub = waver_patrol.bridges.deep_learning_bridge_stub:main',
            'sound_alert_stub = waver_patrol.bridges.sound_alert_stub:main',
            'radar_command_bridge_node = waver_patrol.mission.radar_command_bridge_node:main',
            'target_goal_manager_node = waver_patrol.mission.target_goal_manager_node:main',
            'mission_patrol_manager_node = waver_patrol.mission.mission_patrol_manager_node:main',
            'experiment_data_logger_node = waver_patrol.logging.experiment_data_logger_node:main',
            'simple_sim_odom_node = waver_patrol.test_nodes.simple_sim_odom_node:main',
            'simple_nav2_cmd_sim_node = waver_patrol.test_nodes.simple_nav2_cmd_sim_node:main',
            'gazebo_dynamic_obstacle_node = waver_patrol.test_nodes.gazebo_dynamic_obstacle_node:main',
            'aerial_target_test_publisher_node = waver_patrol.test_nodes.aerial_target_test_publisher_node:main',
            'battery_test_publisher_node = waver_patrol.test_nodes.battery_test_publisher_node:main',
            'lidar_objects_test_publisher_node = waver_patrol.test_nodes.lidar_objects_test_publisher_node:main',
            'radar_target_test_publisher_node = waver_patrol.test_nodes.radar_target_test_publisher_node:main',
            'object_mission_goal_test_publisher_node = waver_patrol.test_nodes.object_mission_goal_test_publisher_node:main',
            'fake_camera_classification_test_publisher_node = waver_patrol.test_nodes.fake_camera_classification_test_publisher_node:main',
        ],
    },
)
